// Complete job roles list
const JOB_ROLES = [
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Software Engineer",
    "Data Analyst",
    "Data Scientist",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Cloud Engineer",
    "Security Engineer",
    "QA Engineer",
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "React Developer",
    "Angular Developer",
    "Vue.js Developer",
    "Node.js Developer",
    "Python Developer",
    "Java Developer",
    "PHP Developer",
    "Ruby on Rails Developer",
    "Go Developer",
    "Rust Developer",
    "C# Developer",
    ".NET Developer",
    "WordPress Developer",
    "Shopify Developer",
    "Salesforce Developer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Data Engineer",
    "Blockchain Developer",
    "Smart Contract Developer",
    "Game Developer",
    "Unity Developer",
    "Unreal Developer",
    "Embedded Systems Engineer",
    "Firmware Engineer",
    "Network Engineer",
    "Database Administrator",
    "System Administrator",
    "IT Support Specialist",
    "Technical Lead",
    "Engineering Manager",
    "Product Manager",
    "Project Manager",
    "Scrum Master",
    "Business Analyst",
    "UX Designer",
    "UI Designer",
    "Graphic Designer",
    "Technical Writer",
    "SEO Specialist",
    "Digital Marketing Specialist",
    "Cybersecurity Analyst",
    "Penetration Tester",
    "Cloud Architect",
    "Solutions Architect",
    "Sales Engineer",
    "Support Engineer",
    "Hardware Engineer",
    "Robotics Engineer",
    "Quantitative Analyst",
    "Database Developer",
    "ETL Developer",
    "BI Developer",
    "CRM Developer",
    "ERP Consultant",
    "SharePoint Developer",
    "Power Platform Developer",
    "Low Code Developer",
    "No Code Developer",
    "AI/ML Engineer",
    "Prompt Engineer",
    "Data Architect",
    "Integration Engineer",
    "Release Manager",
    "Build Engineer",
    "Toolchain Engineer",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Network Architect",
    "Voice Engineer",
    "Collaboration Engineer",
    "CRM Analyst",
    "ERP Analyst",
    "Business Intelligence Analyst",
    "Data Visualization Specialist",
    "Dashboard Developer",
    "Reporting Analyst",
    "ETL Architect",
    "Data Warehouse Engineer",
    "Big Data Engineer",
    "Hadoop Administrator",
    "Spark Developer",
    "Kafka Engineer",
    "Elasticsearch Engineer",
    "MongoDB Developer",
    "PostgreSQL DBA",
    "MySQL DBA",
    "Oracle DBA",
    "SQL Server DBA",
    "Redis Engineer",
    "Cassandra Engineer",
    "Neo4j Developer",
    "Flutter Developer",
    "React Native Developer",
    "Swift Developer",
    "Kotlin Developer",
    "Django Developer",
    "Flask Developer",
    "Spring Boot Developer",
    "Laravel Developer",
    "Rails Developer",
    "ASP.NET Developer",
    "GraphQL Developer",
    "REST API Developer",
    "Microservices Developer",
    "Serverless Developer",
    "Kubernetes Engineer",
    "Docker Engineer",
    "Terraform Engineer",
    "Jenkins Engineer",
    "GitLab CI Engineer",
    "GitHub Actions Developer",
    "Prometheus Engineer",
    "Grafana Developer",
    "Datadog Engineer",
    "Splunk Engineer"
];

// Complete locations list with REMOTE first
const LOCATIONS = [
    "Remote (Worldwide)",
    "Remote - Europe",
    "Remote - Asia",
    "Remote - Americas",
    "Remote - Africa",
    "Remote - Australia/New Zealand",
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "Netherlands",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Belgium",
    "Austria",
    "Ireland",
    "Poland",
    "Czech Republic",
    "Portugal",
    "Greece",
    "Turkey",
    "India",
    "China",
    "Japan",
    "South Korea",
    "Singapore",
    "Malaysia",
    "Thailand",
    "Vietnam",
    "Indonesia",
    "Philippines",
    "United Arab Emirates",
    "Saudi Arabia",
    "Israel",
    "South Africa",
    "Nigeria",
    "Kenya",
    "Egypt",
    "Morocco",
    "Brazil",
    "Mexico",
    "Argentina",
    "Chile",
    "Colombia",
    "Peru",
    "New Zealand",
    "Russia",
    "Ukraine",
    "Romania",
    "Bulgaria",
    "Hungary",
    "Croatia",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Iceland",
    "Luxembourg",
    "Monaco",
    "Andorra",
    "Malta",
    "Cyprus",
    "Bahrain",
    "Qatar",
    "Kuwait",
    "Oman",
    "Jordan",
    "Lebanon",
    "Pakistan",
    "Bangladesh",
    "Sri Lanka",
    "Nepal",
    "San Francisco Bay Area",
    "New York City",
    "Los Angeles",
    "Chicago",
    "Austin",
    "Seattle",
    "Boston",
    "Denver",
    "Atlanta",
    "Miami",
    "London",
    "Manchester",
    "Berlin",
    "Munich",
    "Paris",
    "Amsterdam",
    "Stockholm",
    "Copenhagen",
    "Helsinki",
    "Oslo",
    "Barcelona",
    "Madrid",
    "Milan",
    "Rome",
    "Zurich",
    "Geneva",
    "Vienna",
    "Prague",
    "Warsaw",
    "Krakow",
    "Dublin",
    "Lisbon",
    "Porto",
    "Athens",
    "Istanbul",
    "Tel Aviv",
    "Dubai",
    "Abu Dhabi",
    "Riyadh",
    "Bangalore",
    "Mumbai",
    "Delhi",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Kolkata",
    "Singapore City",
    "Kuala Lumpur",
    "Bangkok",
    "Ho Chi Minh City",
    "Jakarta",
    "Manila",
    "Tokyo",
    "Osaka",
    "Seoul",
    "Beijing",
    "Shanghai",
    "Shenzhen",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Auckland",
    "Cape Town",
    "Johannesburg",
    "Nairobi",
    "Lagos",
    "Cairo",
    "Casablanca",
    "Sao Paulo",
    "Rio de Janeiro",
    "Mexico City",
    "Buenos Aires",
    "Santiago",
    "Bogota",
    "Lima"
];

function getJobRoles() {
    return JOB_ROLES;
}

function getLocations() {
    return LOCATIONS;
}